### ISSUE TITLE
Trying to train teacher.

### ISSUE THREAD

**Issue by bhardwaj1230** [Alibaba-NLP/MultilangStructureKD#1]
Hello,

I read the paper, it was really exciting for me, also I was thinking to replicate the model into my environment.
You have mentioned, an alternative way is training the teacher models by yourself with the below script.. 
Script:  python train_with_teacher.py --config config/multi_bert_origflair_300epoch_2000batch_1lr_256hidden_de_monolingual_crf_sentloss_10patience_baseline_nodev_ner0.yaml

But I don't find the "multi_bert_origflair_300epoch_2000batch_1lr_256hidden_de_monolingual_crf_sentloss_10patience_baseline_nodev_ner0.yaml" file in config.

Can you guide mw how can I train these teachers ?

Regards,
Shiven.

**Comment by wangxinyu0922** [comment]
Hi, I wrote the wrong config file name in README. I'm sorry for that. In fact, the config file is `config/multi_bert_origflair_300epoch_2000batch_0.1lr_256hidden_de_monolingual_crf_sentloss_10patience_baseline_nodev_ner0.yaml`. I have updated the README. Please check the README for more details.

**Comment by bhardwaj1230** [comment]
Hello @wangxinyu0922 

Thanks a lot. Really appreciate you quick responce. 
Also, Can you help me to get the right data for conll_03 ? I know it comes with flair, but I only have Spanish and Dutch data set under .flair/datasets.

When I try to execute : python train_with_teacher.py --config config/multi_bert_300eptilingual_crf_sentloss_10patience_distill_fast_posterior_2.25temperature_old_relearn_nodev_fast_new_ner0.yaml

Error:

2020-12-21 19:47:12.881839: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opene
/home/shivendra/MultilangStructureKD/flair/utils/params.py:104: YAMLLoadWarning: calling yaml.load() without Lder is unsafe. Please read https://msg.pyyaml.org/load for full details.
  dict_merge.dict_merge(params_dict, yaml.load(f))
2020-12-21 19:47:14,404 Reading data from /home/shivendra/.flair/datasets/conll_03_dutch
2020-12-21 19:47:14,404 Train: /home/shivendra/.flair/datasets/conll_03_dutch/ned.train
2020-12-21 19:47:14,405 Dev: /home/shivendra/.flair/datasets/conll_03_dutch/ned.testa
2020-12-21 19:47:14,405 Test: /home/shivendra/.flair/datasets/conll_03_dutch/ned.testb
2020-12-21 19:47:14,405 UTF-8 can't read: /home/shivendra/.flair/datasets/conll_03_dutch/ned.train ... using "
2020-12-21 19:47:18,141 UTF-8 can't read: /home/shivendra/.flair/datasets/conll_03_dutch/ned.testb ... using "
2020-12-21 19:47:19,319 UTF-8 can't read: /home/shivendra/.flair/datasets/conll_03_dutch/ned.testa ... using "
2020-12-21 19:47:20,364 Reading data from /home/shivendra/.flair/datasets/conll_03_spanish
2020-12-21 19:47:20,364 Train: /home/shivendra/.flair/datasets/conll_03_spanish/esp.train
2020-12-21 19:47:20,364 Dev: /home/shivendra/.flair/datasets/conll_03_spanish/esp.testa
2020-12-21 19:47:20,364 Test: /home/shivendra/.flair/datasets/conll_03_spanish/esp.testb
2020-12-21 19:47:20,364 UTF-8 can't read: /home/shivendra/.flair/datasets/conll_03_spanish/esp.train ... using
2020-12-21 19:47:24,180 UTF-8 can't read: /home/shivendra/.flair/datasets/conll_03_spanish/esp.testb ... using
2020-12-21 19:47:24,603 UTF-8 can't read: /home/shivendra/.flair/datasets/conll_03_spanish/esp.testa ... using
2020-12-21 19:47:25,039 --------------------------------------------------------------------------------------
2020-12-21 19:47:25,039 ACHTUNG: CoNLL-03 dataset not found at "/home/shivendra/.flair/datasets/conll_03".
2020-12-21 19:47:25,039 Instructions for obtaining the data can be found here: https://www.clips.uantwerpen.be
2020-12-21 19:47:25,039 --------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "train_with_teacher.py", line 73, in <module>
    config = ConfigParser(config,all=args.all,zero_shot=args.zeroshot,other_shot=args.other,predict=args.predi
  File "/home/shivendra/MultilangStructureKD/flair/config_parser.py", line 63, in __init__
    self.corpus: ListCorpus=self.get_corpus
  File "/home/shivendra/MultilangStructureKD/flair/config_parser.py", line 292, in get_corpus
    current_dataset=getattr(datasets,corpus)(tag_to_bioes=self.target)
  File "/home/shivendra/MultilangStructureKD/flair/datasets.py", line 1362, in __init__
    data_folder, columns, tag_to_bioes=tag_to_bioes, in_memory=in_memory
  File "/home/shivendra/MultilangStructureKD/flair/datasets.py", line 59, in __init__
    for file in data_folder.iterdir():
  File "/home/shivendra/.conda/envs/myenv/lib/python3.7/pathlib.py", line 1107, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/home/shivendra/.flair/datasets/conll_03'

**Comment by wangxinyu0922** [comment]
You may download the ner data [here](https://1drv.ms/u/s!Am53YNAPSsodg88m3q41pypnfHL8zg?e=34ULXy). Move the repository `conll_03_english` to `~/.flair/datasets/` and rename the repository with `conll_03`. (Also for `conll_03_german`)

**Comment by bhardwaj1230** [comment]
Thanks.. It's working now.

**Comment by bhardwaj1230** [comment]
Hello @wangxinyu0922 

I hope you are doing well..

I am sorry to bug you during festive season, but I ran into another issue.
When I run : python train_with_teacher.py --config config/multi_bert_origflair_300epoch_2000batch_0.1lr_256hidden_en_monolingual_crf_sentloss_10patience_baseline_nodev_ner0.yaml

I am facing the url access issue at : /alan-nlp/resources/embeddings-v0.4.1/big-news-forward--h2048-l1-d0.05-lr30-0.25-20/news-forward-0.4.1.pt

Do you know what's causing this ?

Error:
Traceback (most recent call last):
  File "/home/shivendra/.conda/envs/myenv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/shivendra/.conda/envs/myenv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/shivendra/.conda/envs/myenv/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s3.eu-central-1.amazonaws.com', port=443): Max retries exceeded with url: /alan-nlp/resources/embeddings-v0.4.1/big-news-forward--h2048-l1-d0.05-lr30-0.25-20/news-forward-0.4.1.pt (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

**Comment by bhardwaj1230** [comment]
Hello Again..

There is another issue..
When I run the first teacher training script : 
python train_with_teacher.py --config config/multi_bert_origflair_300epoch_2000batch_0.1lr_256hidden_de_monolingual_crf_sentloss_10patience_baseline_nodev_ner0.yaml

Error:
OSError: HEAD request failed for url https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/embeddings/lm-mix-german-forward-v0.2rc.pt with status code 301.


I am not sure why I am getting this error. There might be some issue at flair module itself.
Please let me know you can run the script for the teacher training.

**Comment by bhardwaj1230** [comment]
Resolved this by manually downloading the required flair files from https://nlp.informatik.hu-berlin.de/resources/embeddings/flair/
